WishListProject/WishList/urls.py
from django.urls import path, re_path

from . import views

app_name = 'wishes'

urlpatterns = [
    re_path(r'^delete/(?P<pk>[0-9]+)/$', views.delete, name='delete'),
    path(r'^delete/adm/<str:name>/<int:pk>', views.delete_adm, name='delete_obj_adm'),
]

WishListProject/WishListProject/urls.py
from django.contrib import admin
from django.urls import path, include
from WishList.views import login_page, logout_page, list_of_wishlists, own_wishlist, register_page, register_redirect, delete, delete_adm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_list/', own_wishlist),
    path('login/', login_page),
    path('logout', logout_page),
    path('register/', register_page),
    path('register_redirect', register_redirect),
    path('wish/', include('WishList.urls')),
    path('wish/', include('WishList.urls')),
    path('', list_of_wishlists),
]

WishListProject/WishList/models.py
from random import randint

from django.db import models
from django.db.models import Count


class Object(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)

class Person(models.Model):
    name = models.CharField(max_length=20)
    all_ids = models.JSONField(default=list)

WishListProject/WishList/views.py
import random
from django.contrib.auth.decorators import permission_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Permission
from django.http import JsonResponse, HttpResponse, FileResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from .models import Person, Object
import json
from django.contrib.contenttypes.models import ContentType
from django.template import loader
from django.contrib.auth.models import PermissionsMixin

def login_page(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/')
        return render(request, 'login.html')
    
    if request.method == 'POST':
        username = request.POST.get('login', '')
        password = request.POST.get('password', '')
        
        if username == '' or password == '':
            messages.error(request, 'Заполните все поля!')
            return redirect('/login')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Неправильный логин или пароль!')
            return redirect('/login')
        
        
def register_page(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/')
        return render(request, 'register.html')
    
    if request.method == 'POST':
        username = request.POST.get('login', '')
        password1 = request.POST.get('password', '')
        password2 = request.POST.get('password_check', '')

        if username == '' or password1 == '' or password2 == '':
            messages.error(request, 'Заполните все поля!')
            return redirect('/register')
        if password1 != password2:
            messages.error(request, 'Пароли не совпадают')
            return redirect('/register')

        user = User.objects.create_user(username, '', password1)
        person = Person(name=username)
        person.save()
        user.save()
        return redirect('/')
    else:
        messages.error(request, 'Неправильный логин или пароль!')
        return redirect('/register')


def logout_page(request):
    if request.method == 'POST':
        logout(request)
    return redirect('/login')


def register_redirect(request):
    return redirect('/register')


def own_wishlist(request):
    #TODO
    if request.user.is_authenticated:
        if request.method == 'GET':
            if request.user.is_superuser:
                template = loader.get_template('admin_response.html')
                context = {}
                return HttpResponse(template.render(context, request))
            user = Person.objects.get(name=request.user.username)
            jd = json.JSONDecoder()
            list_of_wishes = jd.decode(str(user.all_ids))
            listw = []
            for wish_id in list_of_wishes:
                obj = get_object_or_404(Object, pk=wish_id)
                listw.append(obj)
            template = loader.get_template('own_wishlist.html')
            context = {
                'list_of_wishes': listw
            }
            return HttpResponse(template.render(context, request))
        
        if request.method == 'POST':
            wish = request.POST.get('wish', '')
            if len(wish) > 30:
                messages.error(request, 'Желание должно быть меньше 30 символов!')
                return redirect('/my_list')
            #TODO find a profanity filter
            obj, created = Object.objects.get_or_create(name=wish, description='username')
            user = Person.objects.get(name=request.user.username)
            jd = json.JSONDecoder()
            je = json.JSONEncoder()
            list_of_wishes = jd.decode(str(user.all_ids))
            if obj.id not in list_of_wishes:
                list_of_wishes.append(obj.id)
            json_of_wishes = je.encode(list_of_wishes)
            user.all_ids = json_of_wishes
            user.save()
            return redirect('/my_list')
    else:
        return redirect('/login')
    

def list_of_wishlists(request):
    #TODO
    if request.user.is_authenticated:
        if request.method == 'GET':
            listoflists = {}
            listofuserids = []
            for i in range(3):
                rand_person = random.choice(Person.objects.all())
                while rand_person.name == request.user.username or rand_person.name in listofuserids:
                    rand_person = random.choice(Person.objects.all())
                listofuserids.append(rand_person.name)
                jd = json.JSONDecoder()
                list_of_random_wishes = jd.decode(str(rand_person.all_ids))
                list_to_die = []
                for wish_id in list_of_random_wishes:
                    obj = get_object_or_404(Object, pk=wish_id)
                    list_to_die.append(obj)
                listoflists[rand_person.name] = list_to_die
            template = loader.get_template('list_of_wishlists.html')
            context = {
                'list_of_lists': listoflists
            }
            return HttpResponse(template.render(context, request))
        
        if request.method == 'POST':
            wishes = request.POST.getlist('bro')
            user = Person.objects.get(name=request.user.username)
            jd = json.JSONDecoder()
            je = json.JSONEncoder()
            list_of_wishes = jd.decode(str(user.all_ids))
            for wish in wishes:
                obj = Object.objects.get(name=wish, description='username')
                if obj.id not in list_of_wishes:
                    list_of_wishes.append(obj.id)
            json_of_wishes = je.encode(list_of_wishes)
            user.all_ids = json_of_wishes
            user.save()
            return redirect('/')
    else:
        return redirect('/login')
    

def delete(request, pk):
    if request.user.is_authenticated:
        if request.method == 'POST':
            user = Person.objects.get(name=request.user.username)
            jd = json.JSONDecoder()
            je = json.JSONEncoder()
            list_of_wishes = jd.decode(str(user.all_ids))
            list_of_wishes.remove(int(pk))
            json_of_wishes = je.encode(list_of_wishes)
            user.all_ids = json_of_wishes
            user.save()
            return redirect('/my_list')
    else:
        return redirect('/login')

def delete_adm(request, name, pk):
    if request.user.is_authenticated:
        if request.method == 'POST':
            if request.user.has_perm('WishList.delete_obj'):
                user = Person.objects.get(name=name)
                jd = json.JSONDecoder()
                je = json.JSONEncoder()
                list_of_wishes = jd.decode(str(user.all_ids))
                list_of_wishes.remove(int(pk))
                json_of_wishes = je.encode(list_of_wishes)
                user.all_ids = json_of_wishes
                user.save()
                return redirect('/')
            else:
                return redirect('/')
    else:
        return redirect('/login')

WishListProject/WishList/templates/admin_response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin_response</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrtiy="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="/">
    <img src="/static/logo.png" width="100" height="50" alt="">
  </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
            </ul>
      <form method="post" action="/logout">
        {% csrf_token %}
        <input type="submit" name="LogOut" class="btn btn-outline-primary" value="Выйти">
      </form>
  </div>
</nav>
<div class="container text-center" align="center">
  Вы являетесь админом, вы не можете добавлять желания или иметь вишлисты
</div>
</body>
</html>

WishListProject/WishList/templates/list_of_wishlists.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Вишлист: Главная</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrtiy="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="/">
    <img src="/static/logo.png" width="100" height="50" alt="">
  </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/">Главная<span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/my_list">Мой вишлист<span class="sr-only"></span></a>
          </li>
            </ul>
      <form method="post" action="/logout">
        {% csrf_token %}
        <input type="submit" name="LogOut" class="btn btn-outline-primary" value="Выйти">
      </form>
  </div>
</nav>
<form method="post">
<div class="container text-center">
  <div class="row align-items-start gx-300">
      {% if list_of_lists %}
      {% for name, list_of_wishes in list_of_lists.items %}
      <div class="col">
        <div class="card border-dark" style="">
            <div class="card-header">{{name}}</div>
            <div class="card-body">
                <ul class="list-group">
                    {%for wish in list_of_wishes%}
                    <li class="list-group-item list-group-item-info">
                        <div class="form-check">
                        <input class="form-check-input me-1" type="checkbox" value="{{wish.name}}" name = "bro" id = "olo">
                        <label class="form-check-label" for="olo"> {{wish.name}}</label>
                        {% if perms.WishList.delete_obj %}
                        <label class="form-check-label" for="olo"> 
                          <form action="{% url 'wishes:delete_obj_adm' name=name pk=wish.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Удалить">
                        </form>
                      </label>
                        {% endif %}
                        </div>
                    </li>
                    {%endfor%}
                </ul>
            </div>
            </div>
        </div>
      {% endfor %}
    {% else %}
      <p>You have not added any wishes.</p>
    {% endif %}
    <div class="col">
    </div>
  </div>
</div>
    {% csrf_token %}
    <div class="container text-right">
            <input type="submit" class="btn btn-primary" value="Добавить в вишлист">
        <p>Выбранные желания можно добавить в вишлист</p>
  </div>
</form>
</body>
</html>

WishListProject/WishList/templates/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Вишлист: Логин</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrtiy="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="/">
    <img src="/static/logo.png" width="100" height="50" alt="">
  </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная<span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/my_list">Мой вишлист<span class="sr-only"></span></a>
      </li>
            </ul>
            <form method="post" action="/logout">
              {% csrf_token %}
              <input type="submit" name="LogOut" class="btn btn-primary" value="Вход">
            </form>
      <form method="post" action="/register_redirect">
    {% csrf_token %}
    <input type="submit" name="Register" class="btn btn-outline-secondary" value="Регистрация">
</form>
      </div>
      </nav>
      <div class="container">
<h1>Вход на сайт</h1>
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class="row">
    <div class="col">
    <label>Логин:</label>
    <input type="text" name="login" class="form-control" placeholder="Введите логин  " autofocus /><br>
    </div>
    </div>
 <div class="form-group">
    <label for="exampleInputPassword1">Пароль:</label>
    <input type="password" placeholder="Введите пароль" class="form-control" id="exampleInputPassword1" name="password"/><br>
 </div>
    <input type="submit" class="btn btn-primary" value="Вход">
    </form>
</div>
</body>
</html>

WishListProject/WishList/templates/own_wishlist.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Вишлист: Мой лист</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrtiy="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="/">
    <img src="/static/logo.png" width="100" height="50" alt="">
  </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная<span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/my_list">Мой вишлист<span class="sr-only"></span></a>
      </li>
            </ul>
      <form method="post" action="/logout">
        {% csrf_token %}
        <input type="submit" name="LogOut" class="btn btn-outline-primary" value="Выйти">
      </form>
  </div>
</nav>
<div class="container text-center">
  <div class="row align-items-start">
    <div class="col">
    </div>
      {% if list_of_wishes %}
      <ul class="list-group">
      {% for wish in list_of_wishes %}
          <li class="list-group-item ">{{ wish.name }} <form action="{% url 'wishes:delete' wish.id %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Удалить">
        </form></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>В вашем вишлисте пока нету желаний.</p>
    {% endif %}
    <div class="col">
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" placeholder="Введите желание" class="form-control" id="exampleInputPassword1" name="wish"/><br>
       </div>
        {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
{% endif %}

      <input type="submit" class="btn btn-primary" value="Добавить в вишлист">
    </form>
    </div>
  </div>
</body>
</html>

WishListProject/WishList/templates/register.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Вишлист: Регистрация</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrtiy="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="/">
    <img src="/static/logo.png" width="100" height="50" alt="">
  </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная<span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/my_list">Мой вишлист<span class="sr-only"></span></a>
      </li>
            </ul>
      <form method="post" action="/logout">
        {% csrf_token %}
        <input type="submit" name="LogOut" class="btn btn-primary" value="Вход">
      </form>
      <form method="post" action="/register_redirect">
        {% csrf_token %}
        <input type="submit" name="Register" class="btn btn-outline-secondary" value="Регистрация">
    </form>
  </div>
</nav>
      <div class="container">
<h1>Регистрация на сайте</h1>
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class="row">
    <div class="col">
    <label>Логин:</label>
    <input type="text" name="login" class="form-control" placeholder="Введите логин" autofocus /><br>
    </div>
    </div>
 <div class="form-group">
    <label for="exampleInputPassword1">Пароль:</label>
    <input type="password" placeholder="Введите пароль" class="form-control" id="exampleInputPassword1" name="password"/><br>
 </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Подтвердите пароль:</label>
    <input type="password" placeholder="Повторите пароль" class="form-control" id="exampleRightInputPassword1" name="password_check"/><br>
 </div>
    <input type="submit" class="btn btn-primary" value="Зарегистрироваться">
</form>
</div>
</body>
</html>